### ISSUE TITLE
好神奇啊，原来可以用中文来做函数的名啊？

### ISSUE THREAD

**Issue by iruletheworld** [suulnnka/BullshitGenerator#3]
这是纯粹的展示用还是真的可以用UICODE字符来做函数名？

**Comment by suulnnka** [comment]
当然可以用中文,实际工程中也可以使用,但是最佳实践还是应该用英文.

**Comment by iruletheworld** [comment]
> 当然可以用中文,实际工程中也可以使用,但是最佳实践还是应该用英文.

多谢解答~真是好神奇啊
