### ISSUE TITLE
想请教一下

### ISSUE THREAD

**Issue by Okarin1024** [suulnnka/BullshitGenerator#5]
想做一个网页版的密码解密工具 按照密钥来解密 已经用c语言实现了 怎么做成在线版呢?

**Comment by suulnnka** [comment]
方法有很多种,这里我只介绍移植的办法.首先学习html+css+javascript,将c语言的每一行代码翻译为javascript,然后用html+css绘制页面,最后将界面和程序关联起来.

这里给你两个参考:
[CyberChef](https://github.com/gchq/CyberChef)
[cryptii](https://github.com/cryptii/cryptii)
